
// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import * as THREE from 'three'
// import { useGLTF, useTexture } from '@react-three/drei'

// export function Building(props) {
//   const { nodes } = useGLTF('models/building1-compression.glb')

//   const facadeTexture = useTexture('/textures/facade.jpg')
//   facadeTexture.flipY = false
//   facadeTexture.colorSpace = THREE.SRGBColorSpace

//   return (
//     <group {...props} dispose={null}>
     

//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.facade.geometry}
//       >
//         <meshBasicMaterial map={facadeTexture} />
//       </mesh>
      
//     </group>
//   )
// }

// useGLTF.preload('/building1-compression.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

export function Building(props) {
  const { nodes } = useGLTF('models/building1-compression.glb')

  const facadeTexture = useTexture('/textures/facade1.2.jpg')
  const condoFloorTexture = useTexture('/textures/condo-floor2.jpg')
  const buildingFloorTexture = useTexture('/textures/building-floor.jpg')
  const whiteWallsTexture = useTexture('/textures/white-walls5.jpg')
  const metalFrames= useTexture('/textures/metal-frames2.jpg')
  const ceiling= useTexture('/textures/ceiling1.2.jpg')
  const furniture1= useTexture('/textures/furniture1.1.jpg')
  const furniture2= useTexture('/textures/furniture2.jpg')
  const furniture3= useTexture('/textures/furniture3.1.jpg')
  const furniture4= useTexture('/textures/furniture4.jpg')
  const garden= useTexture('/textures/garden.jpg')
  const pictures= useTexture('/textures/picture1.2.jpg')


  facadeTexture.flipY = false
  facadeTexture.colorSpace = THREE.SRGBColorSpace
  
  condoFloorTexture.flipY = false
  buildingFloorTexture.flipY = false
  whiteWallsTexture.flipY = false
  metalFrames.flipY = false
  ceiling.flipY = false
  furniture1.flipY = false
  furniture2.flipY = false
  furniture3.flipY = false
  furniture4.flipY = false
  garden.flipY = false
  pictures.flipY = false

  return (
    <group {...props} dispose={null} position={[0, 0, 0]}>
      <mesh
        geometry={nodes.facade.geometry}        
      >
        <meshBasicMaterial map={facadeTexture}/>
      </mesh>


      <mesh
        geometry={nodes['condo-floor'].geometry}        
      >
        <meshBasicMaterial map={condoFloorTexture}/>
      </mesh>


      <mesh
        geometry={nodes['building-floor'].geometry}        
      >
        <meshBasicMaterial map={buildingFloorTexture}/>
      </mesh>


      <mesh
        geometry={nodes['white-walls'].geometry}    
      >
        <meshBasicMaterial map={whiteWallsTexture}/>
      </mesh>


      <mesh
        geometry={nodes.logo.geometry} 
      >
        {/* <meshBasicMaterial map={whiteWallsTexture}/> */}
      </mesh>


      <mesh
        geometry={nodes['metal-frames'].geometry}
      >
        <meshBasicMaterial map={metalFrames}/>
      </mesh>


      <mesh
        geometry={nodes.ceiling.geometry}
      >
        <meshBasicMaterial map={ceiling}/>
      </mesh>
      

      <mesh
        geometry={nodes['furniture-1'].geometry}
      >
        <meshBasicMaterial map={furniture1}/>
      </mesh>


      <mesh
        geometry={nodes['furniture-2'].geometry}
      >
        <meshBasicMaterial map={furniture2}/>
      </mesh>


      <mesh
        geometry={nodes['furniture-3'].geometry}
      >
        <meshBasicMaterial map={furniture3}/>
      </mesh>

      <mesh
        geometry={nodes['furniture-4'].geometry}
      >
        <meshBasicMaterial map={furniture4}/>
      </mesh>

      
      <mesh
        geometry={nodes['garden'].geometry}
      >
        <meshBasicMaterial map={garden}/>
      </mesh>

      <mesh
        geometry={nodes['pictures'].geometry}
      >
        <meshBasicMaterial map={pictures}/>
      </mesh>


    </group>
  )
}

useGLTF.preload('/building1-compression.glb')
